### ISSUE TITLE
Issue regarding Cobra tutorial

### ISSUE THREAD

**Issue by Enzyme5610** [qiuxintao101/cobra#1]
Hello - I am researcher from Buffalo, stumbled upon your workflow for CHIP seq recently. It seems more powerful than Diffbind, and if we get it working - we would not have to rely on other packages to do our analyses.

Trying to learn, new to Docker. Had an issue with the tutorial, I am able to launch cobra and change directory - but I am unable to download the example using the snakemake commands.

I always receive this error:

Error: Snakefile "Snakefile" not present.

**Comment by qiuxintao101** [comment]
Happy to help! Can you try run the "ls" command and post the output? Please post the questions for cobra in the bitbucket issue if possible. https://bitbucket.org/cfce/cobra/issues
